import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WhatsappButton from "@/componentes/helpers/WhatsappBtn";
import ScrollToTopButton from "@/componentes/helpers/ScrollToTopBtn";
import Menu from "@/componentes/menus/Menu";
import Footer from "@/componentes/helpers/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Menu />
        {children}
        <WhatsappButton />
        <ScrollToTopButton />
        <Footer />
      </body>
    </html>
  );
}
